jobs:
  include:

  - stage: "Article service test"
    name: "Article service test"
    dist: xenial
    language: go
    before_script:
    - cd ./services/article
    - go get -d -v
    script: go test

  - stage: "Source service test"
    name: "Source service test"
    dist: xenial
    language: go
    before_script:
    - cd ./services/source
    - go get -d -v
    script: go test

  - stage: build
    name: "Build docker images"
    services:
    - docker
    before_script: cd ./infra/docker/
    script: ls -a

  - stage: deploy
    name: "Deploy to GCP"
    script: echo "Deploy to GCP"
