version: '3.3'

services:

  reverse-proxy:
    image: traefik:v1.7.20-alpine
    ports:
    - 80:80
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ../config/proxy/traefik/traefik.toml:/traefik.toml
    networks:
    - frontend
    - backend
    command:
      --api \
      --docker \
      --logLevel=DEBUG
    deploy:
      placement:
        constraints: [node.role==manager]
      labels:
        traefik.enable: "false"

  source:
    image: ${USERNAME}/source:${SOURCE_SERVICE_VERSION}
    build:
      context: ../../services/source
      dockerfile: Dockerfile
    environment:
    - NEWS_API_KEY=${NEWS_API_KEY}
    labels:
      traefik.frontend.rule: "PathPrefixStrip:/api/source"
      traefik.backend: "source"
      traefik.port: "8081"
      traefik.enable: "true"
      traefik.passHostHeader: "true"
      traefik.docker.network: "backend"
      traefik.frontend.entryPoints: "http"
    networks:
    - backend
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: source.service

  article:
    image: ${USERNAME}/article:${ARTICLE_SERVICE_VERSION}
    build:
      context: ../../services/article
      dockerfile: Dockerfile
    environment:
    - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
    - source
    labels:
      traefik.frontend.rule: "PathPrefixStrip:/api/article"
      traefik.backend: "article"
      traefik.port: "8082"
      traefik.enable: "true"
      traefik.passHostHeader: "true"
      traefik.docker.network: "backend"
      traefik.frontend.entryPoints: "http"
    networks:
    - backend
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: article.service

  ui:
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    build:
      context: ../../services/ui
      dockerfile: Dockerfile
    depends_on:
    - source
    - article
    labels:
      traefik.frontend.rule: "PathPrefixStrip:/"
      traefik.backend: "ui"
      traefik.port: "80"
      traefik.enable: "true"
      traefik.passHostHeader: "true"
      traefik.docker.network: "frontend"
      traefik.frontend.entryPoints: "http"
    networks:
    - frontend
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: ui.service

networks:
  backend:
  frontend:
