version: '3.3'

services:

  source:
    image: ${USERNAME}/source:${SOURCE_SERVICE_VERSION}
    environment:
    - NEWS_API_KEY=${NEWS_API_KEY}
    ports:
    - ${SOURCE_SERVICE_PORT}:8081
    networks:
    - news_aggregator_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.source

  article:
    image: ${USERNAME}/article:${ARTICLE_SERVICE_VERSION}
    environment:
    - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
    - source
    ports:
    - ${ARTICLE_SERVICE_PORT}:8082
    networks:
    - news_aggregator_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.article

  ui:
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    ports:
    - ${UI_SERVICE_PORT}:80
    environment:
    - SOURCE_SERVICE_HOST=source
    - SOURCE_SERVICE_PORT=${SOURCE_SERVICE_PORT}
    - ARTICLE_SERVICE_HOST=article
    - ARTICLE_SERVICE_PORT=${ARTICLE_SERVICE_PORT}
    depends_on:
    - source
    - article
    networks:
    - news_aggregator_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

networks:
  news_aggregator_network:
