version: '3'
services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - "5775:5775/udp"
    - "6831:6831/udp"
    - "6832:6832/udp"
    - "5778:5778"
    - "16686:16686"
    - "14268:14268"
    - "9411:9411"
    networks:
    - backend

  elasticsearch:
    image: elasticsearch:6.8.0
    ports:
    - 9200:9200

  kibana:
    image: kibana:6.8.0
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch

  logstash:
    image: logstash:6.8.0
    ports:
    - 12201:12201/udp
    - 5044:5044
    links:
    - elasticsearch
    depends_on:
    - elasticsearch

networks:
  backend:
