version: '3.3'

services:

  reverse-proxy:
    image: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    networks:
      - frontend
      - backend
    command:
      --api \
      --docker \
      --docker.swarmmode \
      --docker.domain=mysubdomain.notmydomain.com \
      --docker.watch \
      --logLevel=DEBUG
    deploy:
      placement:
        constraints: [node.role==manager]
      labels:
        traefik.enable: "false"

  source:
    image: ${USERNAME}/source:${SOURCE_SERVICE_VERSION}
    build:
      context: ../../services/source
      dockerfile: Dockerfile
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}
    ports:
      - 8081:8081
    deploy:
      labels:
        traefik.enable: "true"
        traefik.backend: "test"
        traefik.docker.network: "cat_traefik-network"
        traefik.frontend.rule: "Host:mysubdomain.notmydomain.com;PathPrefix:/api/source"
        traefik.port: 80
        traefik.frontend.passHostHeader: "true"
        traefik.domain: "mysubdomain.notmydomain.com"
    networks:
      - backend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.source

  article:
    image: ${USERNAME}/article:${ARTICLE_SERVICE_VERSION}
    build:
      context: ../../services/article
      dockerfile: Dockerfile
    environment:
      - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
      - source
    ports:
      - 80:8082
    deploy:
      labels:
        traefik.enable: "true"
        traefik.backend: "test"
        traefik.docker.network: "cat_traefik-network"
        traefik.frontend.rule: "Host:mysubdomain.notmydomain.com;PathPrefix:/api/article"
        traefik.port: 80
        traefik.frontend.passHostHeader: "true"
        traefik.domain: "mysubdomain.notmydomain.com"
    networks:
      - frontend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.article

  ui:
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    build:
      context: ../../services/ui
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - source
      - article
    deploy:
      labels:
        traefik.enable: "true"
        traefik.backend: "test"
        traefik.docker.network: "cat_traefik-network"
        traefik.frontend.rule: "Host:mysubdomain.notmydomain.com;"
        traefik.port: 80
        traefik.frontend.passHostHeader: "true"
        traefik.domain: "mysubdomain.notmydomain.com"
    networks:
      - backend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

networks:
  backend:
  frontend:
