version: '3.3'

services:

  source:
    image: ${USERNAME}/source:${SOURCE_SERVICE_VERSION}
    environment:
    - NEWS_API_KEY=${NEWS_API_KEY}
    ports:
    - 80:8081
    networks:
    - news_aggregator_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.source

  article:
    image: ${USERNAME}/article:${ARTICLE_SERVICE_VERSION}
    environment:
    - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
    - source
    ports:
    - 80:8082
    networks:
    - news_aggregator_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.article

  ui:
    image: ${USERNAME}/ui:${UI_SERVICE_VERSION}
    ports:
    - 80:80
    environment:
    - REACT_APP_SOURCE_HOST=source
    - REACT_APP_ARTICLE_HOST=article
    depends_on:
    - source
    - article
    networks:
    - news_aggregator_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

networks:
  news_aggregator_network:
