apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
    - http:
        paths:
        - path: /grafana
          backend:
            serviceName: grafana
            servicePort: grafana-http
    - http:
        paths:
        - path: /prometheus
          backend:
            serviceName: prometheus-service
            servicePort: prometheus
    - http:
        paths:
        - path: /alertmanager
          backend:
            serviceName: alertmanager
            servicePort: alertmanager
