---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: source
  labels:
    app: source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source
      task: source
  template:
    metadata:
      labels:
        app: source
        task: source
        version: v0.0.1
    spec:
      containers:
      - name: source
        image: danniilperestoronin/source:0.0.1
        env:
        - name: NEWS_API_KEY
          value: "5993d461700e41b89843cb196b68e7cb"
        ports:
        - containerPort: 80
